export Project_Name="project"
#被压缩文件夹的名称
export Project_Path="${HOME}/桌面/project"
#被压缩文件夹的路径
export First_Name="Project"
#压缩文件的第一各名称
export Output_Tar_Project_Path="${HOME}/桌面/qemu_control/"
#压缩后文件应存储的文件夹位置
