name: deploy

on: push

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v2
    
    - name: prepare python
      uses: actions/setup-python@v2

    - name: prepare dependencies
      run: pip install mkdocs-material 

    - name: build docs
      run: mkdocs build

    - name: push to repo
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        branch: gh-pages
        folder: site

